# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kyle/Desktop/dev/main/rtl/verilog/microblaze/microblaze.srcs/sources_1/bd/microblaze_design/ip/microblaze_design_clk_wiz_0_0/microblaze_design_clk_wiz_0_0.xci
# IP: The module: 'microblaze_design_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kyle/Desktop/dev/main/rtl/verilog/microblaze/microblaze.srcs/sources_1/bd/microblaze_design/ip/microblaze_design_clk_wiz_0_0/microblaze_design_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kyle/Desktop/dev/main/rtl/verilog/microblaze/microblaze.srcs/sources_1/bd/microblaze_design/ip/microblaze_design_clk_wiz_0_0/microblaze_design_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kyle/Desktop/dev/main/rtl/verilog/microblaze/microblaze.srcs/sources_1/bd/microblaze_design/ip/microblaze_design_clk_wiz_0_0/microblaze_design_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/kyle/Desktop/dev/main/rtl/verilog/microblaze/microblaze.srcs/sources_1/bd/microblaze_design/ip/microblaze_design_clk_wiz_0_0/microblaze_design_clk_wiz_0_0.xci
# IP: The module: 'microblaze_design_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kyle/Desktop/dev/main/rtl/verilog/microblaze/microblaze.srcs/sources_1/bd/microblaze_design/ip/microblaze_design_clk_wiz_0_0/microblaze_design_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kyle/Desktop/dev/main/rtl/verilog/microblaze/microblaze.srcs/sources_1/bd/microblaze_design/ip/microblaze_design_clk_wiz_0_0/microblaze_design_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/kyle/Desktop/dev/main/rtl/verilog/microblaze/microblaze.srcs/sources_1/bd/microblaze_design/ip/microblaze_design_clk_wiz_0_0/microblaze_design_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_design_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
