FROM ubuntu:latest
MAINTAINER Kyle Neil <kyle@johnneil.net>

WORKDIR /root

SHELL ["/bin/bash", "-c"]

RUN apt-get update --yes

RUN apt-get install --yes gcc g++ golang-go python3 # compilers/interpreters for languages I want
RUN apt-get install --yes libglib2.0-dev # c data structures, cause rolling my own is stupid unless I want to
RUN apt-get install --yes man strace valgrind vim gdb make git binutils check # system/debugging/testing tools
RUN apt-get install --yes flex bison # gnu parse tools
RUN apt-get install --yes autotools-dev autoconf # gnu packaging tools

RUN apt-get install --yes pv # for performance reasons

RUN apt-get update --yes
RUN apt-get upgrade --yes
RUN apt-get dist-upgrade --yes

EXPOSE 80

# build with: docker build -t base .
# run with:
# 	(Windows) docker run -it --rm -v C:\Users\kyle\Desktop\dev\:/root/ -v C:\Users\kyle\:/mnt --privileged --name base base bash
#	(macOS) docker run -it --rm -v /Users/kyleneil/code/main:/root/ -v /Users/kyleneil:/mnt --name base base bash
# to clean "<none>:<none>" files: docker system prune


