FROM ubuntu:latest

WORKDIR /root

SHELL ["/bin/bash", "-c"]

ENV TERM xterm

RUN apt-get update && apt-get install -y \
	bash \
	check \
	gcc \
	g++ \
	gdb \
	clang \
	lldb \
	golang-go \
	python3 \
	libglib2.0-dev \
	strace \
	valgrind \
	vim \
	make \
	git \
	binutils \
	flex \
	bison \
	autotools-dev \
	autoconf \
	autoconf-archive \
&& rm -rf /var/lib/apt/lists/*

EXPOSE 80

# build with: docker build -t base .
# run with:
# 	(Windows) docker run -it --rm -v C:\Users\kyle\Desktop\dev\:/root/ -v C:\Users\kyle\:/mnt --privileged --name base base bash
#	(macOS) docker run -it --rm -v /Users/kyleneil/code/main:/root/ -v /Users/kyleneil:/mnt --name base base bash
# to clean "<none>:<none>" files: docker system prune


