#!/usr/bin/env python3
import sys # for exit
import os # for checking file existance

if __name__ == "__main__":
	print("binary file splitter, by Kyle Neil (1/19)")
	print("for use with 68k EEPROM programmer")
	if (len(sys.argv) < 2):
		print("split <source binary>")
		sys.exit(1)
	try:
		with open(sys.argv[1], "rb") as binsrc:
			bindata = binsrc.read()
	except IOError:
		print("binary cannot be opened!")
		sys.exit(1)
	else:
		print("found binary of size " + str(len(bindata)))
	
	lsbdata = []
	msbdata = []
	
	even = 1
	
	for byte in bindata:
		if even == 0:
			lsbdata.append(byte)
		else:
			msbdata.append(byte)
		even ^= 1

	print("lsb data: ", end='')
	for i in range(0, len(lsbdata)):
		print(hex(lsbdata[i]), end=' ')
	print("")
	
	print("msb data: ", end='')
	for i in range(0, len(msbdata)):
		print(hex(msbdata[i]), end=' ')
	print("")
	
	with open(sys.argv[1] + ".lsb", "wb") as lsb_bin:
		lsb_bin.write(bytes(lsbdata))
	with open(sys.argv[1] + ".msb", "wb") as msb_bin:
		msb_bin.write(bytes(msbdata))
	
	print("done.")
