/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "arith_test.src" instead.
 */

#include <check.h>

#line 1 "arith_test.src"
#include <stdio.h>
#include "proc.h"
#include "execute.h"
#include "dispatch.h" // used to test r0 writes, since individual functions don't
			 // handle it


#line 9
proc *p;

enum registers {
	R0,
	R1,
	R2,
	R3,
	R4,
	R5,
	R6,
};

void proc_set_vec(proc *p) {
	for (int i = 0; i < 32; i++) {
		p->regfile[i] = i;
	}
	
	p->i.f_s0 = R1;
	p->i.f_s1 = R2;
	p->i.f_d = R3;
}

// lots of identical code here, should really clean this up
// no isolation argument because check already does that



START_TEST(add_1)
{
#line 38
	p->i.f_d = R3;
	
	p->regfile[R1] = 44;
	p->regfile[R2] = 32;

	instr_add(p);
	
	ck_assert_int_eq(p->regfile[R3], 76);

}
END_TEST

START_TEST(add_2)
{
#line 48
	p->i.f_d = R3;
	
	instr_add(p);
	
	ck_assert_int_eq(p->regfile[R3], 3);

}
END_TEST

START_TEST(add_b)
{
#line 55
	p->i.f_pm = 0b010;
	
	p->regfile[R1] = 0x00FF;
	p->regfile[R2] = 0x0001;
	
	instr_add(p);
	ck_assert_int_eq(p->regfile[R3], 0);
	
}
END_TEST
	
START_TEST(add_dest_r0)
{
#line 66
	proc *p = malloc(sizeof(proc));
	proc_set_vec(p);
	
	p->i.f_d = R0;
	p->i.f_opcode = ADD;

	int err = disp(p, NULL); // not executing an instruction that needs RAM
	
	ck_assert_int_eq(p->regfile[R0], 0);
	ck_assert_int_eq(err, 0);

}
END_TEST

START_TEST(mul_1)
{
#line 80
	p->i.g_s0 = R6;
	p->i.g_s1 = R6;
	
	p->i.g_l = R3;
	p->i.g_h = R4;
	
	instr_mul(p);
	
	ck_assert_int_eq(p->regfile[R3], 36);

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("fives-check");
    TCase *tc1_1 = tcase_create("add_instr");
    TCase *tc1_2 = tcase_create("dest_r0");
    TCase *tc1_3 = tcase_create("instr_mul");
    SRunner *sr = srunner_create(s1);
    int nf;

    /* User-specified pre-run code */
#line 91
	p = malloc(sizeof(proc));
	proc_set_vec(p);

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, add_1);
    tcase_add_test(tc1_1, add_2);
    tcase_add_test(tc1_1, add_b);
    suite_add_tcase(s1, tc1_2);
    tcase_add_test(tc1_2, add_dest_r0);
    suite_add_tcase(s1, tc1_3);
    tcase_add_test(tc1_3, mul_1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
