/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "branch.src" instead.
 */

#include <check.h>

#line 1 "branch.src"
#include "test.h"



START_TEST(unconditional_branch_32b)
{
#line 8
    proc *p = malloc(sizeof(proc));
    proc_set_vec(p);

    p->regfile[R3] = 0xAAFF;
    instr_stu(p);

    p->i.b_imm = 0x1111;
    instr_bn(p);

    ck_assert_int_eq(p->PC, 0xAAFF1111);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("branch-check");
    TCase *tc1_1 = tcase_create("branch");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, unconditional_branch_32b);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
