/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "cntl.src" instead.
 */

#include <check.h>

#line 1 "cntl.src"
#include "test.h"
	
	

START_TEST(nop)
{
#line 8
    proc *p = calloc(1, sizeof(proc)); // important to make sure no stray bytes are different
    proc_set_vec(p);

    proc *p2 = malloc(sizeof(proc));
    proc_set_vec(p2);

    int code = instr_nop(p2);

    ck_assert_int_eq(code, RET_OK);
    ck_assert_int_eq(memcmp(p2, p, sizeof(p)), 0); // make sure it did nothing

}
END_TEST

START_TEST(stop)
{
#line 20
    proc *p = malloc(sizeof(proc));
    proc_set_vec(p);

    int code = instr_stop(p);
    ck_assert_int_eq(code, RET_STOP);
	

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("cntl-check");
    TCase *tc1_1 = tcase_create("cntl");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, nop);
    tcase_add_test(tc1_1, stop);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
