FROM alpine:latest

WORKDIR /root

ENV TERM xterm

RUN apk add --no-cache bash \
			gcc \
			g++ \
			go \
			python3 \
			glib \
			man \
			strace \
			valgrind \
			vim \
			gdb \
			make \
			git \
			binutils \
			flex \
			bison \
			automake \
			autoconf \
			pv

EXPOSE 80

SHELL ["/bin/bash", "-c"]

# build with: docker build -t base .
# run with:
# 	(Windows) docker run -it --rm -v C:\Users\kyle\Desktop\dev\:/root/ -v C:\Users\kyle\:/mnt --privileged --name base base bash
#	(macOS) docker run -it --rm -v /Users/kyleneil/code/main:/root/ -v /Users/kyleneil:/mnt --name base base bash
# to clean "<none>:<none>" files: docker system prune


