# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/microblaze_design/microblaze_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design || ORIG_REF_NAME==microblaze_design} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_axi_gpio_0_0/microblaze_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_axi_gpio_0_0 || ORIG_REF_NAME==microblaze_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_clk_wiz_0_0/microblaze_design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_clk_wiz_0_0 || ORIG_REF_NAME==microblaze_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_microblaze_0_0/microblaze_design_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_microblaze_0_0 || ORIG_REF_NAME==microblaze_design_microblaze_0_0} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_mdm_1_0/microblaze_design_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_mdm_1_0 || ORIG_REF_NAME==microblaze_design_mdm_1_0} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_rst_clk_wiz_0_100M_0/microblaze_design_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==microblaze_design_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_microblaze_0_axi_periph_0/microblaze_design_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblaze_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_dlmb_v10_0/microblaze_design_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_dlmb_v10_0 || ORIG_REF_NAME==microblaze_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_ilmb_v10_0/microblaze_design_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_ilmb_v10_0 || ORIG_REF_NAME==microblaze_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_dlmb_bram_if_cntlr_0/microblaze_design_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_ilmb_bram_if_cntlr_0/microblaze_design_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_design/ip/microblaze_design_lmb_bram_0/microblaze_design_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_design_lmb_bram_0 || ORIG_REF_NAME==microblaze_design_lmb_bram_0} -quiet] -quiet

# XDC: bd/microblaze_design/microblaze_design_ooc.xdc
